-- PCEA Ngecha Mother Church
-- PostgreSQL schema and baseline seed data
-- Target DB: pcea_ngecha

-- 1) Create database (run as superuser in psql)
-- CREATE DATABASE pcea_ngecha;
-- \connect pcea_ngecha;

-- 2) Core tables
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ministers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    title VARCHAR(80) NOT NULL,
    bio TEXT,
    photo_url VARCHAR(500),
    email VARCHAR(255),
    phone VARCHAR(30),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_reverend BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS districts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description TEXT,
    image_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS elders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    photo_url VARCHAR(500),
    bio TEXT,
    email VARCHAR(255),
    phone VARCHAR(30),
    district_id INTEGER UNIQUE REFERENCES districts(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deacons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    photo_url VARCHAR(500),
    email VARCHAR(255),
    phone VARCHAR(30),
    zone VARCHAR(80),
    district_id INTEGER NOT NULL REFERENCES districts(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(30),
    district_id INTEGER NOT NULL REFERENCES districts(id) ON DELETE RESTRICT,
    date_joined DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS church_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    category VARCHAR(80),
    description TEXT,
    patron_elder_id INTEGER REFERENCES elders(id) ON DELETE SET NULL,
    image_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_officers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES church_groups(id) ON DELETE CASCADE,
    member_name VARCHAR(150) NOT NULL,
    position VARCHAR(80) NOT NULL,
    year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2100),
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sermons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    minister_id INTEGER NOT NULL REFERENCES ministers(id) ON DELETE RESTRICT,
    preached_on DATE NOT NULL,
    scripture VARCHAR(120),
    audio_url VARCHAR(500),
    video_url VARCHAR(500),
    description TEXT,
    sermon_series VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    event_time TIME,
    venue VARCHAR(200),
    image_url VARCHAR(500),
    group_id INTEGER REFERENCES church_groups(id) ON DELETE SET NULL,
    district_id INTEGER REFERENCES districts(id) ON DELETE SET NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    district_id INTEGER REFERENCES districts(id) ON DELETE SET NULL,
    group_id INTEGER REFERENCES church_groups(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS albums (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    event_date DATE,
    cover_image_url VARCHAR(500),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gallery (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS donations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name VARCHAR(150) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    method VARCHAR(80) NOT NULL,
    reference VARCHAR(120) UNIQUE,
    donated_on DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prayer_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255),
    request_text TEXT NOT NULL,
    is_answered BOOLEAN NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(150),
    subscribed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3) Performance indexes
CREATE INDEX IF NOT EXISTS idx_members_district_id ON members(district_id);
CREATE INDEX IF NOT EXISTS idx_deacons_district_id ON deacons(district_id);
CREATE INDEX IF NOT EXISTS idx_elders_district_id ON elders(district_id);
CREATE INDEX IF NOT EXISTS idx_church_groups_patron_elder_id ON church_groups(patron_elder_id);
CREATE INDEX IF NOT EXISTS idx_group_officers_group_id ON group_officers(group_id);
CREATE INDEX IF NOT EXISTS idx_sermons_minister_id ON sermons(minister_id);
CREATE INDEX IF NOT EXISTS idx_sermons_preached_on ON sermons(preached_on DESC);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_group_id ON events(group_id);
CREATE INDEX IF NOT EXISTS idx_events_district_id ON events(district_id);
CREATE INDEX IF NOT EXISTS idx_announcements_start_date ON announcements(start_date DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_district_id ON announcements(district_id);
CREATE INDEX IF NOT EXISTS idx_announcements_group_id ON announcements(group_id);
CREATE INDEX IF NOT EXISTS idx_gallery_album_id ON gallery(album_id);
CREATE INDEX IF NOT EXISTS idx_prayer_requests_submitted_at ON prayer_requests(submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_contact_messages_submitted_at ON contact_messages(submitted_at DESC);

-- 4) Keep updated_at current on every update
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    table_name TEXT;
    trigger_name TEXT;
    managed_tables TEXT[] := ARRAY[
        'users',
        'ministers',
        'districts',
        'elders',
        'deacons',
        'members',
        'church_groups',
        'group_officers',
        'sermons',
        'events',
        'announcements',
        'albums',
        'gallery',
        'donations',
        'prayer_requests',
        'newsletter_subscribers',
        'contact_messages'
    ];
BEGIN
    FOREACH table_name IN ARRAY managed_tables LOOP
        trigger_name := format('trg_%s_updated_at', table_name);

        IF EXISTS (
            SELECT 1
            FROM pg_trigger t
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE t.tgname = trigger_name
              AND c.relname = table_name
              AND n.nspname = current_schema()
        ) THEN
            EXECUTE format('DROP TRIGGER %I ON %I', trigger_name, table_name);
        END IF;

        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            trigger_name,
            table_name
        );
    END LOOP;
END;
$$;

-- 5) Baseline seed data
INSERT INTO districts (name, is_active)
VALUES
    ('Judea', TRUE),
    ('Jerusalem', TRUE),
    ('Zion', TRUE),
    ('Samaria', TRUE),
    ('Jordan', TRUE),
    ('Canaan', TRUE),
    ('Jericho', TRUE),
    ('Bethsaida', TRUE),
    ('Bethlehem', TRUE),
    ('Israel', TRUE),
    ('Nazareth', TRUE),
    ('Galilee', TRUE),
    ('Macedonia', TRUE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO church_groups (name, is_active)
VALUES
    ('Women''s Guild (PWG)', TRUE),
    ('Presbyterian Men''s Fellowship (PCMF)', TRUE),
    ('Youth Fellowship', TRUE),
    ('Church School (Sunday School)', TRUE),
    ('Boys Brigade', TRUE),
    ('Girls Brigade', TRUE),
    ('Church Choir', TRUE),
    ('Evangelism Committee', TRUE),
    ('Health Board', TRUE),
    ('JPRC', TRUE),
    ('Christian Education Committee', TRUE),
    ('Development Committee', TRUE)
ON CONFLICT (name) DO NOTHING;

-- Optional: create admin user after generating a proper werkzeug hash.
-- INSERT INTO users (name, email, password_hash, role, is_active)
-- VALUES ('System Administrator', 'admin@pceangecha.co.ke', 'REPLACE_WITH_WERKZEUG_HASH', 'admin', TRUE)
-- ON CONFLICT (email) DO NOTHING;
